org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=1G -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
kotlin.code.style=official
org.gradle.caching=true
org.gradle.parallel=true
org.gradle.tooling.parallel=true
org.gradle.configuration-cache=true
org.gradle.configuration-cache.parallel=true